name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build with make
      run: |
        cd Day_1
        make
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake git
    - name: Clone and build GoogleTest
      run: |
        git clone https://github.com/google/googletest.git
        cd googletest
        mkdir build
        cd build
        cmake ..
        make
    - name: Build and run gtest
      run: |
        g++ -DUNIT_TEST -std=c++17 -Igoogletest/googletest/include -pthread Day_1/test_swap.c Day_1/Swap_two_num.c googletest/build/lib/libgtest.a -o Day_1/test_swap_runner
        ./Day_1/test_swap_runner
    - name: Run the program
      run: |
        cd Day_1
        ./Swap_two_num
    - name: Build and run atoi tests
      run: |
        g++ -DUNIT_TEST -std=c++17 -Igoogletest/googletest/include -pthread Day_2/test_atoi.cpp Day_2/atoi.cpp googletest/build/lib/libgtest.a -o Day_2/test_atoi_runner
        ./Day_2/test_atoi_runner
    - name: Build atoi binary
      run: |
        g++ -g -o Day_2/atoi Day_2/atoi.cpp
    - name: Run the program
      env:
        ATIO_INPUT: "5"
      run: |
        cd Day_2
        ./atoi $ATIO_INPUT
    - name: Build and run addtwonum
      run: |
        g++ -DUNIT_TEST -std=c++17 -Igoogletest/googletest/include -pthread Day_3/test_addtwonum.c Day_3/addtwonum.c googletest/build/lib/libgtest.a -o Day_3/test_addtwonum_runner
        ./Day_3/test_addtwonum_runner